In [1]:
import numpy as np
import pandas as pd
import re

In [ ]:
df = pd.read_csv('51job.csv',encoding='gbk')
df = df.drop_duplicates()
df = df[df.职位.str.contains(r'.*?数据.*?|.*?分析.*?')]#提取包含数据或者分析的岗位

In [ ]:
def remove_str(df):
    for i in range(0, df.shape[0]):
        for j in range(0, df.shape[1]):
            df.iloc[i][j] = df.iloc[i][j][2:-2]#直接选取字符串中的第一个到最后一个字符，简单方便
            #df.iloc[i][j] = df.iloc[i][j].strip(('['']'))只能去掉外面的中括号
    return df#已经去掉了外面的方框，之后看看怎么把引号去掉

In [ ]:
df = remove_str(df)
df.head()
df.to_excel('finished.xlsx')

In [ ]:
df2 = df.薪资.str.extractall('(\d*\.?\d)([-](\d?\.?\d))')
df2.to_excel('df2.xlsx')

In [2]:
df3 = pd.read_excel('finished.xlsx',encoding='gbk')
df4 = pd.read_excel('df2.xlsx')
df4.head()
data = pd.concat([df3,df4],axis=1)
#data.to_excel('合并.xlsx')

In [5]:
for i in range(data.shape[0]):
    if u'万' in data.薪资[i] and u'年' in data.薪资[i]:
        data.工资下限[i] = float(data.工资下限[i]) / 12 * 10
        data.工资上限[i] = float(data.工资上限[i]) / 12 * 10
    elif u'万' in data.薪资[i] and u'月' in data.薪资[i]:
        data.工资下限[i] = float(data.工资下限[i]) * 10
        data.工资上限[i] = float(data.工资上限[i]) * 10

D:\Anaconda\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

D:\Anaconda\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys

KeyError: 16

In [6]:
data

,职位,薪资,公司,公司信息,公司地址,地区,工作经验,学历,人数,时间,岗位信息,工资下限,工资上限
0,大数据开发工程师,1-2.5万/月,苏州瑞翼信息技术有限公司,民营公司| 150-500人| 通信/电信运营、增值服务 互联网/电子商务,上班地址 : 苏州工业园区星湖街328号 创意产业园6-301单元,苏州-工业园区,本科,NaN,4人,2019-02-22,职责：1、基于Hadoop/Spark的大数据处理和分析平台的架构和开发；2、负责分析新的数...,10.0,25.0
1,大数据开发工程师,1-1.5万/月,广州优亿信息科技有限公司,民营公司| 50-150人| 通信/电信/网络设备 通信/电信运营、增值服务,上班地址 : 越秀区广东广播中心大楼,广州,2年工作经验,本科,2人,2019-02-22,职责:1.按照项目计划，配合项目经理，按时提交高质量代码，完成开发任务；2.规范文档的编写、...,10.0,15.0
2,(DSP项目)数据开发工程师,1.5-2.5万/月,上海高欣计算机系统有限公司,民营公司| 500-1000人| 计算机软件 互联网/电子商务,上班地址 : 银冬路491号2幢,上海-浦东新区,2年工作经验,本科,1人,2019-02-22,参与/负责数据仓库ETL（数据抽取、加载、清洗、转换）处理任务的设计和开发工作2. 参与/...,15.0,25.0
3,数据开发工程师,3-8千/月,杭州煎饼网络技术有限公司,民营公司| 150-500人| 互联网/电子商务 金融/投资/证券,上班地址 : 西湖区双龙街199号金色西溪B座6层,杭州,本科,NaN,1人,2019-02-22,职责：1、维护爬虫程序2、研究反爬策略3、维护数据分析处理程序4、参与部分大数据开发职位要求...,3.0,8.0
4,大数据开发工程师,0.5-1万/月,合肥斡亿信息科技有限公司,民营公司| 50-150人| 计算机软件 互联网/电子商务,上班地址 : 创新大道2800号创新产业园二期F4楼4层,合肥-高新区,2年工作经验,本科,3人,2019-02-22,职责：1、负责各种网络数据的采集、清洗、整合工作；2、负责大数据的分布式存储和管理工作；3、...,5.0,10.0
5,大数据开发工程师,0.8-1.3万/月,重庆森鑫炬科技有限公司,民营公司| 50-150人| 计算机软件,上班地址 : 上清寺环球互联网广场13楼ABCF座,重庆-渝中区,NaN,NaN,1人,2019-02-22,职责：1.负责大数据平台的开发、维护工作；2.负责大数据采集、清洗、整合等工作；3.负责大数...,8.0,13.0
6,大数据开发工程师,1-2.5万/月,宝德融资租赁（上海）有限公司,民营公司| 1000-5000人| 金融/投资/证券 租赁服务,上班地址 : 福山路388号越秀大厦308,上海-浦东新区,3-4年工作经验,本科,2人,2019-02-22,职责：1、负责大数据平台的搭建、发布部署及相关维护工作；2、负责大数据平台和集群的预警和监控...,10.0,25.0
7,大数据开发工程师,3-6万/月,北京恩穗企业咨询有限责任公司,民营公司| 少于50人| 专业服务(咨询、人力资源、财会),上班地址 : 星创科技广场,上海-浦东新区,3-4年工作经验,本科,2人,2019-02-22,职责：1. 负责基于Hadoop开源系统的大数据平台设计、开发、维护。2. 开发统一平台，负...,30.0,60.0
8,大数据开发工程师,1-2万/月,杭州小桃微集网络科技有限公司,民营公司| 50-150人| 互联网/电子商务,上班地址 : 高德置地中心1号楼35F,杭州-江干区,3-4年工作经验,本科,1人,2019-02-22,要求：1、负责公司内数据分析需求的开发工作，及相关沟通；2、负责大数据平台系统的建设管理工作...,10.0,20.0
9,资深数据开发工程师 （西安),1.5-2万/月,杭州数云信息技术有限公司,民营公司| 150-500人| 互联网/电子商务 计算机软件,上班地址 : 高新三路人保大厦1807室,西安-雁塔区,5-7年工作经验,大专,2人,2019-02-22,描述： 1.负责离线计算平台的开发和维护工作； 2.负责HBase/TiDB的开发与维护...,15.0,20.0
10,大数据开发工程师,0.8-1.5万/月,安徽之达大数据研究院有限公司,民营公司| 150-500人| 计算机服务(系统、数据服务、维修) 计算机软件,上班地址 : 合肥市包河区兰州路88号安徽青年电子商务产业园A、B座9层,合肥-包河区,1年工作经验,大专,3人,2019-02-22,职责：1、负责大数据应用平台底层框架的整体架构设计，分析和结合公司实际业务情况进行技术选型及...,8.0,15.0
11,大数据开发工程师,1-2.5万/月,上海高重信息科技有限公司,民营公司| 50-150人| 计算机软件 计算机服务(系统、数据服务、维修),上班地址 : 滨湖区太湖新城金融一街平安财富中心1005室,无锡-滨湖区,3-4年工作经验,本科,3人,2019-02-22,职责：1、图像数据快速存储及检索的开发和优化；2、大数据平台的设计和构建职位要求：1、本科及...,10.0,25.0
12,大数据开发工程师（久其智通）,1-1.5万/月,北京久其软件股份有限公司,上市公司| 1000-5000人| 计算机软件,上班地址 : 北京市西直门国英一号楼,北京-西城区,本科,NaN,1人,2019-02-22,描述：1.负责大数据产品模块设计及开发，撰写技术文档。 岗位要求：1、本科及以上学历，计算机...,10.0,15.0
13,大数据开发工程师,1-1.5万/月,上海爱数信息技术股份有限公司,民营公司| 500-1000人| 计算机软件 计算机服务(系统、数据服务、维修),上班地址 : 长沙市高新区麓谷大道627号长海创业基地B1栋6楼西侧爱数,长沙-岳麓区,无工作经验,硕士,5人,2019-02-22,职责：负责数据提取、清理分析工作；负责大数据挖掘分析算法以及功能的实现任职要求：1、硕士或以...,10.0,15.0
14,大数据开发工程师,2-4万/月,阅文集团,上市公司| 1000-5000人| 互联网/电子商务,上班地址 : 碧波路690号6号楼,上海-浦东新区,本科,NaN,1人,2019-02-22,职责:负责大数据BI设计和开发；负责阅文日常数据统计分析；数据仓库、数据集市的模型设计与开发...,20.0,40.0
15,数据开发工程师,1-1.5万/月,上海启林投资管理有限公司,民营公司| 少于50人| 金融/投资/证券 计算机软件,上班地址 : 新地大厦A座1807,合肥-政务区,本科,NaN,2人,2019-02-22,描述：1. 开发数据生产、管理流程和框架，监控数据实时性和准确性；2. 开发模型分析数据，为...,10.0,15.0
17,大数据开发工程师,1.5-2万/月,西安德创人力资源咨询有限公司,民营公司| 少于50人| 专业服务(咨询、人力资源、财会),上班地址 : 西安市高新区锦业路,西安,3-4年工作经验,本科,若干人,2019-02-22,描述1、负责大数据相关开发和Java相关研发工作；2、负责存储、查询、导入等相关模块的对接开...,1.5,2.0
18,大数据开发工程师,0.6-1.2万/月,湖南千盟物联信息技术有限公司,民营公司| 150-500人| 电子技术/半导体/集成电路 计算机软件,上班地址 : 麓谷大道627号新长海中心B3栋601,长沙-岳麓区,3-4年工作经验,本科,2人,2019-02-22,职责：1、负责公司大数据可视化及产品应用开发；2、负责公司大数据平台过程中设计文档撰写；3、...,0.6,1.2
19,大数据开发工程师,2-4万/月,上海虎宝网络科技有限公司,创业公司| 50-150人| 互联网/电子商务,上班地址 : 漕河泾开发区莘砖公路668号1101室,上海-松江区,3-4年工作经验,本科,1人,2019-02-22,负责公司大数据整体方案的设计和规划，包括大数据应用平台的设计、搭建和持续优化；2、参与计算框...,2.0,4.0
20,大数据开发工程师（项目经理）,0.6-1万/月,南京弦歌信息技术有限公司,民营公司| 150-500人| 计算机软件,上班地址 : 人民路8号 陕西国防工业职业技术学院,西安-鄠邑区,3-4年工作经验,本科,1人,2019-02-22,负责软件开发项目的管理工作，制定项目计划和控制项目进度；2、承担项目的业务梳理及相关设计工作...,0.6,1.0
21,大数据开发工程师,1-2万/月,上海摩莱信息科技有限公司,民营公司| 少于50人| 计算机软件 互联网/电子商务,上班地址 : 临新路268弄扬子江国际企业广场17号楼502-1,上海-长宁区,1年工作经验,大专,4人,2019-02-22,"计算机相关专业,本科以上学历。至少1年以上大数据相关开发经验2：熟悉java，scala或者...",1.0,2.0
22,大数据开发项目经理,15-30万/年,义乌中国小商品城信息技术有限公司,国企| 50-150人| 计算机服务(系统、数据服务、维修) 互联网/电子商务,上班地址 : 义乌,义乌,NaN,NaN,1人,2019-02-22,基于业务需求和应用场景，设计和实现公司大数据相关产品；2、负责大数据平台架构规划、设计与实施...,15.0,30.0
23,大数据开发工程师,0.8-1万/月,安徽康嘉乐健康产业有限公司,民营公司| 50-150人| 医疗/护理/卫生 多元化业务集团公司,上班地址 : 经开区经典广场8层,合肥-经开区,2年工作经验,本科,1人,2019-02-22,职责1、参与大规模数据快速查询系统的架构设计和开发；2、大规模数据挖掘和机器学习算法的实现；...,0.8,1.0

In [ ]:
def get_salary(salary):
    if '-'in salary:  # 针对1-2万/月或者10-20万/年的情况，包含-
        low_salary = re.findall(re.compile('(\d*\.?\d+)'), salary)[0]
        high_salary = re.findall(re.compile('(\d?\.?\d+)'), salary)[1]
        if u'万' in salary and u'年' in salary:  # 单位统一成千/月的形式
            low_salary = float(low_salary) / 12 * 10
            high_salary = float(high_salary) / 12 * 10
        elif u'万' in salary and u'月' in salary:
            low_salary = float(low_salary) * 10
            high_salary = float(high_salary) * 10
    else:  # 针对20万以上/年和100元/天这种情况，不包含-，取最低工资，没有最高工资
        low_salary = re.findall(re.compile('(\d*\.?\d+)'), salary)[0]
        high_salary = ""
        if u'万' in salary and u'年' in salary:  # 单位统一成千/月的形式
            low_salary = float(low_salary) / 12 * 10
        elif u'万' in salary and u'月' in salary:
            low_salary = float(low_salary) * 10
        elif u'元'in salary and u'天'in salary:
            low_salary = float(low_salary)/1000*21  # 每月工作日21天
    return low_salary, high_salary